using PawliceAndPurrglar.Config;
using PawliceAndPurrglar.Gameplay.Items;
using PawliceAndPurrglar.Gameplay.Loot;
using UnityEngine;

namespace PawliceAndPurrglar.UI
{
    /// <summary>
    /// Turns the two kinds of thing a slot can hold into tooltip words.
    ///
    /// The mapping and nothing else. Every sentence about a prop comes from
    /// <see cref="ThrowableCatalog"/>, beside the durations it quotes, and every
    /// sentence about treasure is derived from fields the
    /// <see cref="LootDefinition"/> already carries. Nothing here asks what an
    /// item is by name — the thing this class exists to prevent is the
    /// <c>if (item.name == "Banana")</c> that would otherwise appear in a slot.
    ///
    /// Treasure deliberately grew no new serialized fields. Thirty-odd
    /// definitions are generated by <c>LootDataSetup</c> and validated by
    /// <c>LootSetupValidator</c>; adding a description field would mean thirty
    /// assets to author and thirty chances for one to be left blank, when rarity
    /// and carry type already say the two things the thief needs to hear.
    /// </summary>
    public static class ItemTooltipCatalog
    {
        public static ItemTooltipContent ForProp(ThrowableKind kind, Sprite icon)
        {
            return new ItemTooltipContent(
                icon,
                ThrowableCatalog.GetDisplayName(kind),
                ThrowableCatalog.GetCategoryLabel(kind),
                ThrowableCatalog.GetShortDescription(kind),
                ThrowableCatalog.GetUsageHint(kind));
        }

        public static ItemTooltipContent ForLoot(
            LootDefinition definition,
            Sprite icon)
        {
            return definition == null
                ? default
                : new ItemTooltipContent(
                    icon,
                    definition.DisplayName,
                    GetLootCategory(definition.Rarity),
                    GetLootDescription(definition),
                    LootUsageHint);
        }

        /// <summary>
        /// What kind of treasure it is, said as its rarity.
        ///
        /// The rarity is the only thing that separates two pieces of loot in the
        /// rules — it is what the raccoon pays on — so it is what the category
        /// line should carry. The price itself stays out of the tooltip and
        /// belongs in the merchant's ledger, where the player is deciding about
        /// money rather than about weight.
        /// </summary>
        private static string GetLootCategory(LootRarity rarity)
        {
            return rarity switch
            {
                LootRarity.Uncommon => UncommonCategory,
                LootRarity.Rare => RareCategory,
                _ => CommonCategory
            };
        }

        /// <summary>
        /// What carrying it costs, and whether lifting it wakes the town.
        ///
        /// Eight cached sentences — four carry types times alarm or no alarm —
        /// rather than a string built per call, because the bag rebinds every
        /// frame.
        /// </summary>
        private static string GetLootDescription(LootDefinition definition)
        {
            int carry = (int)definition.CarryType;
            if (carry < 0 || carry >= CarryDescriptions.Length)
            {
                carry = (int)LootCarryType.OneHand;
            }

            return definition.RaisesAlarm
                ? AlarmedCarryDescriptions[carry]
                : CarryDescriptions[carry];
        }

        private const string CommonCategory = "보통 보물";
        private const string UncommonCategory = "고급 보물";
        private const string RareCategory = "희귀 보물";

        private const string LootUsageHint = "너구리 상인에게 판매 · Q : 내려놓기";

        private const string AlarmSuffix = " 훔치면 경보가 울립니다.";

        private static readonly string[] CarryDescriptions =
        {
            "주머니에 들어가 속도가 줄지 않습니다.",
            "한 손으로 들어 조금 느려집니다.",
            "양손으로 들어 많이 느려집니다.",
            "짐짝이라 아주 느려집니다."
        };

        private static readonly string[] AlarmedCarryDescriptions =
        {
            CarryDescriptions[0] + AlarmSuffix,
            CarryDescriptions[1] + AlarmSuffix,
            CarryDescriptions[2] + AlarmSuffix,
            CarryDescriptions[3] + AlarmSuffix
        };
    }
}
